### 1. Matrices
- Basic definition: rectangular array of numbers
- Tensors (PyTorch)
- Ndarrays (NumPy)
### 1.1 Creating Matrices

In [1]:
import numpy as np

In [2]:
# Creating a 2x2 array
arr = [[1,2],[3,4]]
print(arr)

[[1, 2], [3, 4]]


In [3]:
# Convert to NumPy
arr=np.array(arr)

array([[1, 2],
       [3, 4]])

In [4]:
import torch

In [20]:
# Convert to PyTorch Tensor
arr=torch.Tensor(arr)
print(arr)
print(type(arr))

tensor([[1., 2.],
        [3., 4.]])
<class 'torch.Tensor'>


### 1.2 Create Matrices with Default Values

In [6]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [7]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [8]:
np.random.rand(2,2)

array([[0.69371519, 0.82996822],
       [0.0742768 , 0.27348994]])

In [9]:
torch.rand((2,2))

tensor([[0.8837, 0.6586],
        [0.1545, 0.2335]])

### 1.3 Seed for Reproducibility

In [23]:
# Seed
np.random.seed(0)
x=np.random.rand(2,2)
print(x)
np.random.seed(0)
np.random.rand(2,2)

[[0.5488135  0.71518937]
 [0.60276338 0.54488318]]


array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [11]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [12]:
####### GPU SEED #######
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

### 1.4 Numpy and Torch Bridge
#### NumPy to Torch


In [13]:
# Numpy array
np_array = np.ones((2, 2))
print(np_array)

[[1. 1.]
 [1. 1.]]


In [14]:
print(type(np_array))
# Convert to Torch Tensor
torch_tensor = torch.from_numpy(np_array)
print(type(torch_tensor))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [15]:
np_array_new = np.ones((2,2), dtype=np.int8)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)

#### The conversion supports:
1. double
2. float
3. int64,int32,in8,uint8

In [16]:
# Data types matter
np_array_new = np.ones((2,2), dtype=np.int64) # gen
np_array_new=torch.from_numpy(np_array_new) # to torch -> LONG TENSOR
print(type(np_array_new))
np_array_new = np.ones((2,2), dtype=np.int32) # gen
np_array_new=torch.from_numpy(np_array_new) # to torch
print(type(np_array_new))
np_array_new = np.ones((2,2), dtype=np.uint8) # gen
np_array_new=torch.from_numpy(np_array_new) # to torch 
print(type(np_array_new))
np_array_new = np.ones((2,2), dtype=np.float64) # gen
np_array_new=torch.from_numpy(np_array_new) # to torch 
print(type(np_array_new))
np_array_new = np.ones((2,2), dtype=np.float32) # gen
np_array_new=torch.from_numpy(np_array_new) # to torch 
print(type(np_array_new))

<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>


#### TOrch to Numpy

In [24]:
print(type(torch_tensor))
torch_to_numpy=torch_tensor.numpy()
print(type(torch_to_numpy))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


## CPU GPU 

In [25]:
# CPU 
tensor_cpu = torch.ones(3,3)

# CPU TO GPU
if torch.cuda.is_available():
    tensor_cpu.cuda()

# GPU TO CPU
tensor_cpu.cpu()

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### Tensor operations
#### Resizing tensors

In [26]:
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [27]:
#
print(a.size())
a.view(4)
a.view(4).size()

# Element-vise addition
a = torch.ones(2,2)
b = torch.ones(2,2)
c = a + b

# Element-vise addition
c = torch.add(a, b)

# In palce addtion
print('Old tensor: \n', c)

c.add_(a) # add a to c

print('-'*60)
print('New c tensor:')
print(c)

torch.Size([2, 2])
Old tensor: 
 tensor([[2., 2.],
        [2., 2.]])
------------------------------------------------------------
New c tensor:
tensor([[3., 3.],
        [3., 3.]])


In [28]:
# Element-wise sustraction
b=torch.ones(2,2)
a=torch.ones(2,2)
# print(a.sub(b))
# print(a.sub_(b)) 

a=torch.ones(2,2)
a=a*2
b=b*3
print(a)
print(b)
print(torch.mul(a,b))

# Element-wise division
a=torch.ones(2,2)
b=torch.zeros(2,2)
b /a
torch.div(b,a)
b.div_(a)


tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[6., 6.],
        [6., 6.]])


tensor([[0., 0.],
        [0., 0.]])

In [29]:

# tensor mean
a = torch.Tensor((1,2,3,4,5,6,7,8,9,10))
a.size()
a=a.mean(dim=0) # dimension , 1 dimension
print(a)
# a.mean(dim=1) # onyl 1 dimension - > error

tensor(5.5000)


In [30]:
a = torch.Tensor([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
a.size()
a.mean(dim=1) # mean across the lists


tensor([5.5000, 5.5000])

### Tensor Standard Deviation

In [31]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9.10])
a.std(dim=0)


tensor(2.7570)